properties:
  template:
    containers:
    - env:
      - name: RAILS_ENV
        value: development
      - name: CW_API_ONLY_SERVER
        value: "true"
      - name: DATABASE_URL
        value: postgresql://chatwootuser:ChatwootSecure2025!@chatwoot-db-fresh.postgres.database.azure.com/chatwoot_shared?options=-csearch_path%3Ddevelopment
      - name: DATABASE_SCHEMA
        value: development
      - name: SHARED_DATABASE_NAME
        value: chatwoot_shared
      - name: REDIS_URL
        value: redis://localhost:6379
      - name: SECRET_KEY_BASE
        value: 6c2b6b1b8f8b1b1b8f8b1b1b8f8b1b1b8f8b1b1b8f8b1b1b8f8b1b1b8f8b1b1b
      - name: FRONTEND_URL
        value: https://chatwoot-backend-test.calmmushroom-30b1c815.eastus.azurecontainerapps.io
      - name: FORCE_SSL
        value: "false"
      - name: RAILS_LOG_TO_STDOUT
        value: "true"
      - name: MAILER_SENDER_EMAIL
        value: noreply@yourdomain.com
      - name: SMTP_DOMAIN
        value: yourdomain.com
      - name: ENABLE_ACCOUNT_SIGNUP
        value: "false"
      - name: SKIP_DATABASE_CREATION
        value: "true"
      - name: SIDEKIQ_CONCURRENCY
        value: "2"
      - name: ENABLE_DEBUG_TOOLBAR
        value: "true"
      - name: ENABLE_TEST_WEBHOOKS
        value: "true"
      - name: SKIP_SSL_VERIFICATION
        value: "true" 