# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
:timeout: 25
:max_retries: 3

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
# https://github.com/sidekiq/sidekiq/wiki/Advanced-Options
# Using weighted queues ensures all queues are processed, with higher weights processed more frequently
# This prevents low priority jobs from being starved when higher priority queues have jobs
:queues:
  - [critical, 10]
  - [high, 8]
  - [medium, 6]
  - [default, 4]
  - [mailers, 3]
  - [action_mailbox_routing, 2]
  - [low, 1]
  - [scheduled_jobs, 2]
  - [async_database_migration, 1]
  - [active_storage_analysis, 1]
  - [active_storage_purge, 1]
  - [action_mailbox_incineration, 1]

# you can override concurrency based on environment
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
staging:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
